#!/usr/bin/env bash
echo "== list 5 newest buckets script"

# Passes the aws command to jq - a command-line JSON procsessor
## .Buckets accesses the Buckets field in the JSON output
## sort_by(.creationDate) does what the name suggests
## 'reverse' reverses the order of the buckets
## limits number of buckets to show up to 5
## .[] iterates over each item in the array of buckets
## .Name extracts the "NMame" field from each bucket object
aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[0:5] | .[] | .Name'
echo ... 