#!/usr/bin/env bash

echo "== sync bash script"

### Error Handler ###
# Exit immediately if a command exits with a non-zero status
set -e

# Function to handle errors
error_handler() {
    echo "Error occurred in script at line: $1"
}

# Trap errors and call the error_handler function with the line number where the error occurred
trap 'error_handler $LINENO' ERR
###

# Check if there is an argument for a bucket name
if [ -z $1 ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

# Check if there is an argument for a filename prefix
if [ -z $2 ]; then
    echo "There needs to be a filanem prefix  eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

# Where we'll store these files
OUTPUT_DIR="/tmp/s3-bash-scripts"

# remove folder if it already exists
rm -r $OUTPUT_DIR

# Create output folder
mkdir -p $OUTPUT_DIR

# Generate a random number to determine how many files to create
NUM_FILES=$((RANDOM % 6 + 5)) 

for ((i=1; i<=$NUM_FILES; i++)); do
    # Generate a random filename
    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}${i}.txt"

    # Generate random data and write it to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files